baseURL = "http://localhost:1313"
#baseURL = "https://chinglinwen.github.io/hugotest"
languageCode = "en-us"
title = "Chinglin's blog"

publishDir = "docs"
#theme = "hugo-lithium-theme"
theme = "ananke"
